#! /bin/bash 

#sudo check
#intro text
createDirsVars
#text
getInstallJava
#text
getInstallShootOFF
#text
updatePermissions
#text
addLaunchFunction
#text
removeTmpFiles
#text
finalCheck
# if [ finalCheck ] 
closingStatement



function createDirsVars() { 
	SHOOTOFF=~/.ShootOFF
	tmpSHOOTOFF=/tmp/ShootOFFnukeWhenDone
	mkdir $SHOOTOFF
	mkdir $tmpSHOOTOFF
	USER=$USER
}


function getInstallJava() {
	sudo add-apt-repository ppa:webupd8team/java -y 
	sudo apt-get update
	echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
	echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
	sudo apt-get -y install oracle-java8-installer 
}


function getInstallShootOFF() {
	wget -c https://github.com/phrack/ShootOFF/releases/download/v3.10-FINAL/shootoff-3.10-final.zip -P $tmpSHOOTOFF
	unzip $tmpSHOOTOFF/shootoff-3.10-final.zip -d $SHOOTOFF
}


function updatePermissions() { 
	sudo chown -R $USER:$USER $SHOOTOFF 
	sudo chmod 777 $SHOOTOFF/shootoff.properties
	sudo chmod 777 $SHOOTOFF/ShootOFF.jar
}

function addLaunchFunction() {
	cat > $tmpSHOOTOFF/updateBashRC.txt <<EOL
		function ShootOFF() {
			export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libv4l/v4l1compat.so;
			cd ~/.ShootOFF	
			java -jar ShootOFF.jar;
		}
EOL
# adding function from $tmpSHOOTOFF into user's bashrc @ 644
cat $tmpSHOOTOFF/updateBashRC.txt >> ~/.bashrc
}


function removeTmpFiles () {
	sudo rm -rv $tmpSHOOTOFF
}


function finalCheck() {
	## are the install files deleted
	## can we access certain files and directories
}

function closingStatement() {
	printf "\n\n\n**************************************************\n"
	printf "ShootOFF has been installed on this system!\n" 
	printf "\nIf you would like to use the software please launch with the desktop icon\n"
	printf "or simply type ShootOFF into the terminal\n" 
	printf "MAKE SURE YOUR WEBCAM IS PLUGGED IN :)\n" 
	printf "\nIf you enjoy the project, please consider donating to Project Appleseed\n"
	printf "at www.appleseedinfo.org\n\n"
	printf "**************************************************\n\n\n"
}
